### ISSUE TITLE
Trigger FlowCard rejecting in run listener does not stop flow execution

### ISSUE THREAD

**Issue by Shakesbeard** [athombv/apps-sdk-issues#179]
Returning a Promise.reject from the runListner still makes the flow execute.
Returning false prevents flow execution though. Either docu wrong or bug.

**Comment by mrlukasbos** [comment]
Could you please provide more details - perhaps an example of what you are trying to do?

In the docs at https://apps-sdk-v3.developer.athom.com/tutorial-Flow.html under the header "Listening for events", it is explicitly stated that either `true` or `false` must be returned in order for the Flow the continue or stop. Since the listener in the example is `async` in fact a Promise<boolean> is returned. So this boolean value can indeed only be given in a `resolve()` But in the JSDoc reference https://apps-sdk-v3.developer.athom.com/FlowCardCondition.html#registerRunListener it is stated that the result must `resolve()` in order for the Flow to execute. This is indeed a little bit strange (we will look into it) but I'm not entirely sure if this is your issue. 

EDIT:
Apparently I have missed the Discussion in Slack about this issue. - We're on it

**Comment by jeroenwienk** [comment]
https://athomcommunity.slack.com/archives/C04SUGZ9E/p1615128162345000

**Comment by tjallingt** [comment]
Should be fixed in a homey release coming soon :)
