### ISSUE TITLE
ApiApp throws exception when endpoints return un-JSON-serializable data

### ISSUE THREAD

**Issue by robertklep** [athombv/apps-sdk-issues#184]
When an ApiApp instance calls an API endpoint (of another app), and that endpoint returns something that cannot be JSON-serialized (like `undefined`), an exception is thrown by ApiApp (`Error: invalid json response body at Remote Process`).

It's not documented anywhere that API endpoints should return data that's JSON-serializable.

**Comment by tjallingt** [comment]
Nice, thanks for reporting!

Do I understand correctly this error happens in the app that performs the call (client), not the one providing the data (server)?
In that case I think we should also print a warning when an api returns data that doesn't json serialize, so the developer of the app in question can spot, and fix, it more easily.

**Comment by robertklep** [comment]
Correct, the client gets the exception.

Warning on the server side sounds like a good idea 👍🏻

**Comment by tjallingt** [comment]
So actually the issue was that we internally turn `undefined` into a `204 No Content` response but the client tried to parse that as JSON. I added a check so that a 204 status code gets turned back into `undefined` as expected. I'm going to take a look at the documentation and see if we can explain this behaviour clearer.
