### ISSUE TITLE
Missing device detail hook.

### ISSUE THREAD

**Issue by koktaildotcom** [athombv/apps-sdk-issues#201]
It's more an improvement than a bug.

When entering a device detail (capacity UI details) there is no way to hook into that process is it?

I have a usecase with my app xiami mi flora. The devices are synced on a time interval. But I would like that if you enter the details of the device that an ble connection is made to show real-time data.

An hook to an device would be awesome.

Public onDeviceDetailEvent() in the device or something.

**Comment by tjallingt** [comment]
I'm not sure I understand what you want to do and why that's not possible right now. Can you explain which device details you mean? Do you mean you want to know in the app when the capability screen is opened in the front-end?

![Screenshot 2021-04-27 at 15 16 22](https://user-images.githubusercontent.com/5736783/116247883-951d5980-a76b-11eb-8f95-92bfae47db61.png)

**Comment by koktaildotcom** [comment]
Yes! That is exactly what I meant. Is this already possible in the current version?

**Comment by koktaildotcom** [comment]
I don't want every device to update, only the one that is opened in the app.

**Comment by tjallingt** [comment]
> Is this already possible in the current version?

No, at this time there are no special events when a user interacts with device from the front-end (other than actions such as changing capability values of course). 

Its' an interesting idea, if it is something many apps can benefit from we could implement this but I'm not sure for how many apps this would be useful. The best way to help us determine whether we should add this is to collect use-cases; Homey Apps that could benefit from this feature and list them here.

I'm closing this issue now because it is not an active bug but if you have/find more use-cases for a feature like this please do share them here!
