### ISSUE TITLE
Homey update broke my app/Wrong app validation

### ISSUE THREAD

**Issue by MadMonkey87** [athombv/apps-sdk-issues#221]
My app supports several switches that have a "raw_switch_event" trigger flow card. As each button has slightly different tokens and arguments each device has it's own trigger card but they have all the same id  "raw_switch_event". As a result the generated app.json contains multiple "raw_switch_event" cards but they do not conflict because each has a different device filter:
`          {
            "type": "device",
            "name": "device",
            "filter": "driver_id=aqara-button-gyro"
          },
`

For the past that worked pretty well but now it won't succeed the validation and gives me the following error:
`× Homey App did not validate against level `publish`:
Found multiple Flow card triggers with the id "raw_switch_event", all Flow cards should have a unique id.`

So I guess it actually would work pretty well as it always did, but a new validation prevents me from installing or publishing the app. I also cannot rename the flow cards because that would break all existing installations!

The only solution I see is that Athom either drops this validation or improves it by not only checking for duplicate flow card id's but rather check in detail if there is really a conflict, i.e. if there are duplicate flow card id's AND matching device filters. Or what can I do to solve this issue?

**Comment by tjallingt** [comment]
Yea this behaviour is pretty unfortunate, your Flow cards worked correctly but having multiple Flow cards with the same `id` was a potential cause of very hard to debug issues so we decided to disallow it.
The recommended fix is to create a single Flow card definition in `/.homeycompose/flow/triggers/raw_switch_event.json` where you set the `"filter": "driver_id=aqara-button-gyro|other-driver-id|..."` manually.

Hope this helps!

**Comment by tjallingt** [comment]
> As each button has slightly different tokens and arguments

Oh this detail makes that impossible... That is very unfortunate. I'll need to think about this for a bit.

**Comment by tjallingt** [comment]
We discussed this internally, having Flow cards with duplicate ids is too much of a footgun for developers and is tricky to support for us.
Therefore my original recommendation stands; you should create a single Flow card with a filter for multiple `driver_id`s.
If the Flow cards require different tokens/arguments you need to create new Flow cards with unique ids. 

For existing users of your app nothing should change if you remove the Flow cards from the manifest without changing the code. This means that, if you don't change the Flow card "run listener", removing these Flow cards should be backwards compatible.

**Comment by MadMonkey87** [comment]
Sorry your approch for existing installations does not work
![Screenshot_20210921-150807_Homey.png](https://user-images.githubusercontent.com/29612400/134176102-815f80b7-b2db-444b-820b-2f0c6db351ee.png)

**Comment by MadMonkey87** [comment]
As mentioned above, the recommended approach does not work and all affected flows are broken. 

To be honest:

- You already created a pr https://github.com/athombv/node-homey-lib/pull/312 that would fix the issue, why can you not just improve this one and not just check for unique id's but rather check that there are no conflicting ones. For example that there are not two flow cards with the same id and driver filter? Should be quiet easy
- Why does Athom bring in such things? This is a pure virtual problem
- Before this was working perfectly fine and was fully within the officially allowed specifications. Of course Athom can change that but why not provide a migration path then?
- @WeeJeWel is always complaining about bad quality of the apps, but behaviour like that is causing this. In this example (assumed the suggested workaround would work) the app- and code quality does suffer because I would need to basically support a lot of legacy triggers while having new ones, duplicating a lot of code etc

PLEASE PROVIDE A PROPER SOLUTION FOR THIS ISSUE OR NO APP UPDATES ARE POSSIBLE

**Comment by tjallingt** [comment]
Hey Philippe,

I'm sorry, I really thought that would work but I was confusing the ways Flow cards and capabilities work. I should have thought that through more.

Given that there appears no real workaround for this issue we've decided to downgrade this to a warning for SDK v2 apps. We're keeping this as an error for the SDK v3 apps for now. This should mean you can update your app again.

> why can you not just improve this one and not just check for unique id's but rather check that there are no conflicting ones. For example that there are not two flow cards with the same id and driver filter? [...]

Yea we could do that but we really do want to warn when Flow cards use duplicate IDs. As I've mentioned before, Flow cards with duplicate IDs can cause really difficult to understand/debug issues.

The SDK is not able to differentiate between different "device Flow cards" with the same ID, therefore you can only have 1 "run listener" per Flow card id.

Perhaps it would be possible to "fix" the SDK but it would likely make defining Flow cards more complex. We really want to make app development simpler. Additionally we need to not break existing apps so we would be limited in the changes we could make.

So we made defining Flow cards with duplicate IDs an error since we believed it to be an improvement, and we thought that all apps with this error could be migrated/"fixed". Unfortunately this turned out not to be the case.

We are sorry that this wasn't communicated clearly and that it prevented you from updating your app.

**Comment by MadMonkey87** [comment]
AS mentioned in https://github.com/athombv/homey-apps-sdk-issues/issues/222 this issue is not yet resolved!
