### ISSUE TITLE
`homey` CLI uses incorrect/misleading app size

### ISSUE THREAD

**Issue by robertklep** [athombv/apps-sdk-issues#244]
I found that one of my test apps was taking considerably long to upload (using `homey app run`) than another test app, even though the first app reported a smaller app size.

It turns out that the app size that is reported by `homey app run` is based on the file size of the tar file that gets generated. I think the developer assumed that the size of the tar file is (more or less) the combined size of the files contained within it.

However, the tar file size doesn't match up with how much actual disk space gets taken up. With 4K IO blocks on a typical modern filesystem, a lot of small files (as you would have with a typical Node.js app) will take up a lot more actual disk space than the combined file sizes. And because Homey's I/O doesn't seem to be very fast, this has a real impact.

I created two test apps, `helloworld1` and `helloworld2`. They differ only in that in the `helloworld1` directory there's a 1MB file, and in the `helloworld2` directory there's a directory with 250 1-byte files.

The respective app sizes using `du` (which shows actual disk usage) shows the directories are about the same size (250 files each taking up 4K is 1MB in total):
```
3996	name.klep.helloworld1/
3972	name.klep.helloworld2/
```

Uploading `helloworld1`:
```
$ homey app run
…
 — App size: 1.02 MB
…
✓ Homey App `name.klep.helloworld1` successfully installed (took 0.348s)
```

Uploading `helloworld2`:
```
$ homey app run
…
 — App size: 266 KB
…
✓ Homey App `name.klep.helloworld1` successfully installed (took  1.787s)
```

Even though the reported app size for `helloworld2` is a quarter of that of `helloworld1`, it takes 5x longer to upload (you'd expect it to be about the same given the actual disk sizes, so I can only assume that the additional I/O caused by writing those 250 files is taking up the rest of the time).

**Comment by koktaildotcom** [comment]
I recenty have some long waits for running apps too. I only added some extra icons to the app and it becomes 3x slower.

**Comment by tjallingt** [comment]
Hey,

As you observed the reported size is the size of the archive. This measure is more indicative of data usage/speed of the download rather than extraction duration/usage on disk. The overhead of extracting and creating a lot of tiny files is indeed a larger influence on the installation when installing an app (especially locally) giving a "wrong" impression.

If app size was a more important metric we should probably measure the combined size of the unarchived files but at the moment I'm not sure thats worth it. If you feel like that is important/useful information to please let us know!

When taking a look at this I did see that we could easily report the number of archived files which seems like an interesting metric to report so I opened a PR for that.

Hope this helps

**Comment by robertklep** [comment]
It's not very difficult to track the combined file sizes:
```
    let filesSize = 0;
    await pipeline(
      tar.pack(path.join(this.path, '.homeybuild'), { 
        dereference: true,
        map: header => {
          filesSize += header.size;
          return header;
        }
      }).on('data', chunk => {
        appSize += chunk.length;
      }),
      zlib.createGzip(),
      fs.createWriteStream(tmpFile.path),
    );
```

However, it's not a very useful metric because it doesn't reflect the actual disk space the app will take, nor does it give an idea on how long it will take for the app to install (which is proportional to the number of files that have to be installed).

**Comment by tjallingt** [comment]
Right the `header` also contains the file size, clever!

All metrics we can collect/report will be just an indication, its tricky to decide what will be the most intuitive 😕 
I think reporting number of files is probably a good addition and maybe we should update the text to say 
`App archive size: 1.02 MB`
so it is clearer that its not the size on disk.

Do you agree? If so I'll close the issue :) otherwise I'd love to hear your thoughts

**Comment by robertklep** [comment]
Fair enough, I think it's not possible to determine in any meaningful way how long it will take for an app to install, but at least showing the number of files would provide a bit of a clue on how long it might take.

**Comment by WeeJeWel** [comment]
Deployed in the latest `node-homey`.
