### ISSUE TITLE
polling greenwave nodes

### ISSUE THREAD

**Issue by irritanterik** [athombv/apps-sdk-issues#29]
I'm not allowed to report issues on repo https://github.com/athombv/com.greenwavesystems 
Major function of the greenwave powernodes is 'realtime' power consumption monitoring. It seems this is removed since V2 rewrite. Energy values on devices are not updated for 7 days now (based on V2 android app). So my homey is still thinking my TV is on and lights are off. (based on situation 7 day's ago).

**Comment by WeeJeWel** [comment]
This is not a bug but intended. The greenwave device doesn't follow the Z-Wave spec (it doesn't report), and as result we noticed that many Z-Wave networks became unstable due to the polling of the device, resulting in angry users and a ton of support issues. That is why we made the decision to remove the polling functionality.

You can ofcourse sideload a previous version of the app, the code is open-source.

**Comment by irritanterik** [comment]
Is there a way to request a power consumption update by flow? I had no troubles with these devices in my large (60+ nodes) leave network. Had an poll interval of 5-10 minuten. 
Will install the old version indead, is that one compatible with Homey V2?

**Comment by WeeJeWel** [comment]
There's no functionality like that currently built in the greenwave app. And the old one works on Homey v2.0.
